### ISSUE TITLE
Some modules are missing

### ISSUE THREAD

**Issue by AlexDaniel** [moritz/perl6-all-modules#2]
IIRC some modules were missing from this repository. What was the issue and what is its status?

**Comment by JJ** [comment]
There are 315 modules here, far as I can tell.

**Comment by zoffixznet** [comment]
@moritz ping.

Any way to rectify this issue? This repo is commonly used to for looking at how commonly various constructs are used, among other things...

**Comment by moritz** [comment]
This is the tail of the log:

```
Subrepo 'github/perl6/whateverable' is up to date.
git-subrepo: Command failed: 'git ls-remote git://gitlab.com/pheix/router-right-perl6.git'.
git-subrepo: Command failed: 'git ls-remote git@github.com:tony-o/perl6-event-emitter-interprocess.git'.
git-subrepo: Command failed: 'git ls-remote git@github.com:edumentab/p6-ecma262regex.git'.
Subrepo 'https://github.com/tmtvl/Zodiac-Chinese.git' (master) cloned into 'github/tmtvl/Zodiac-Chinese'.
Removing cpan/ELIZABETH/subs
fatal: pathspec 'cpan/ELIZABETH/subs' did not match any files
The spawned command 'git' exited unsuccessfully (exit code: 128)
  in sub MAIN at _tools/populate.p6 line 67
  in block <unit> at _tools/populate.p6 line 3

```

**Comment by AlexDaniel** [comment]
https://github.com/moritz/perl6-all-modules/blob/30f26ad105b5227fb62345c2b8f9950f24cc0491/_tools/populate.p6#L67

https://docs.perl6.org/language/traps#Sunk_Proc

**Comment by moritz** [comment]
I just found out I had my `git subrepo` repo on an unmerged bugfix branch, which seems to have broken lots of other things.

I'm now trying with a master `git subrepo` again, it seems to work better.

**Comment by moritz** [comment]
There are now 318 modules in this repo (used to be more around 215 before I fixed stuff).

Given some loss from modules whose URL might not be up-to-date anymore, I'd consider this a success.

**Comment by moritz** [comment]
Sorry, I miscounted; 1197 repos.

(I counted the source/author combinations, not source/author/module).
